# Generated by Django 3.0.8 on 2020-07-16 14:07

from django.db import migrations

def create_initial_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    groups = [Group(name=name) for name in ['Student', 'Teacher', 'CourseOwner']]
    Group.objects.bulk_create(groups)


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0011_update_proxy_permissions'), 
        ('accounts', '0004_auto_20200710_1410')
    ]

    operations = [
        migrations.RunPython(create_initial_groups),
    ]






