# Generated by Django 3.0.8 on 2020-07-13 15:16

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid_token, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(default='No description yet')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
